[package]
name = "musicpd"
version = "0.1.0"
authors = ["Richard Dodd <richard.o.dodd@gmail.com>"]

[dependencies]
nom = "*"
chrono = "*"
semver = "*"
futures = "*"
tokio-core = "*"

[features]
default = [ ]
verbose-errors = [ "nom/verbose-errors" ]
